### ISSUE TITLE
Changes in Layer Manager #2

### ISSUE THREAD

**Issue by PavelHajek** [hslayers/project-agro-climatic#10]
Could I ask for more minor changes in the Layer Manager and related things?
 The description of a particular agro-climatic factor is under the "Settings" button. Could setting and a description be separated? The settings (cluster, distance, legend, opacity do not seem to work at all, so there is no need to keep them in the settings).
For example, having the description of a factor as a part of the "hover mouse" element would be nice. If not, can the icon be changed from gears into an "i" icon? If it stays the same, then the word "Abstract" can be omitted from the description.

**Comment by raitisbe** [comment]
Im afraid we cant change the icon, but i will put the abstract as a hover tooltip so we dont have to click the layer to see it.

**Comment by raitisbe** [comment]
Tooltip is done

**Comment by PavelHajek** [comment]
> Tooltip is done

And it looks great, thanks ;-)...
