### ISSUE TITLE
Cutting plane -to enable view inside the field of bars (nice to have)

### ISSUE THREAD

**Issue by smrcek** [hslayers/project-agro-climatic#2]
R: how do you solve that that in the middle of country the stacks are occluded by the front bars?

K: Usually there is some "cutting plane" functionality implemented - so you can go in the dataset, by hiding a part of it (ideally interactively). 

Example here: https://helpcenter.graphisoft.com/wp-content/uploads/ac21_help/03-2-views-virtual-building/3DCut1.png

**Comment by raitisbe** [comment]
https://drive.google.com/file/d/15v9_yNdU9gdyHxFcFU7oh3jqZJhmvIE9/view
