### ISSUE TITLE
Timelime by years

### ISSUE THREAD

**Issue by PavelHajek** [hslayers/project-agro-climatic#3]
It would be nice to have a timeline stepping by the whole year, not by a rapid movement of time on time slider in order to have better control over time by the user.

**Comment by raitisbe** [comment]
I will look if its possible. Sometimes cesium timeline is a bit unyielding

**Comment by PavelHajek** [comment]
This kind of timeline looks good for our purposes: https://cesium.com/blog/images/2018/03-19/Wildfires.gif. Would it be possible to have just years on the bar?

**Comment by PavelHajek** [comment]
The starting year of the timeline could be in 2019.

**Comment by raitisbe** [comment]
Looks that they have developed their own timeline from scratch
