### ISSUE TITLE
Changes in the Layer Manager

### ISSUE THREAD

**Issue by PavelHajek** [hslayers/project-agro-climatic#6]
I would like to ask you if the order of the layers in the Layer Manager tab could be altered?
The contemporary state is this:
![image](https://user-images.githubusercontent.com/17336075/95201028-a149c580-07df-11eb-8afe-0fe89abc60dc.png)
I would propose such changes in names, in the order of these two groups of layers and I would also add a kind of an "info" button describing a factor (either by hovering a mouse over or by clicking on), which would be helpful for a user. I try to explain the proposed changes in the following text (**bold** = title of a layer; _italic_ = content of info button; at the end of a paragraph in brackets is a name and hexadecimal code of color for symbolization such a factor:

Agro-climatic factors (formerly Map Content)
related to environmental variables (formerly conditions)
**Frost-free period [in days]** (_Time period between last spring frost date and first fall frost date of the year._)  (Clay - #813f0b)
**Water balance [in millimeters per year]** (_Value of evapotranspiration and runoff subtracted from precipitation._) (Leave the symbology the way it is right now)
**Solar radiation [in MJ/m2/year]** (_Total yearly solar energy received at the Earth’s surface._) (Yellow - #fff200)
**Soil temperatures for fertilization [in days/date]** (_Last fall dates determining when ammonium nitrogen fertilization can be applied without excessive nitrification during the autumn and winter when the soil temperature turns below 10 °C._) (Royal - #7852a9)
**Heat stress units [number]** (_A summary of maximum daily temperatures higher than the absolute maximum temperature for crop growth - occurs only in some years in this area of interest._) (Red - #d30000)
related to length of (optimal) growing period of a crop (formerly yield) - (green for non-optimal length - #3bb143, sea green for Optimal length - #2e8b57)
**LGP for C3 crops [in days]** (_LGP stands for Length of Growing Period and is calculated as a sum of days when the average temperature is in between the absolute minimum and the absolute maximum of the selected crop.
C3 crops are understood as plants that survive solely on C3 fixation, i.e. have no special features to combat photorespiration, such as cereals._)
**LOGP for C3 crops [in days]** (_LOGP stands for Length of Optimal Growing Period and it is calculated as a sum of days when the average daily temperature is at the best temperatures for crop growth, between the optimal minimum and optimal maximum of the selected crop.
C3 crops are understood as plants that survive solely on C3 fixation, i.e. have no special features to combat photorespiration, such as cereals._)
**LGP and LOGP for C3 crops [in days]** (_LGP stands for Length of Growing Period and is calculated as a sum of days when the average temperature is in between the absolute minimum and the absolute maximum of the selected crop.
LOGP stands for Length of Optimal Growing Period and it is calculated as a sum of days when the average daily temperature is at the best temperatures for crop growth, between the optimal minimum and optimal maximum of the selected crop.
C3 crops are understood as plants that survive solely on C3 fixation, i.e. have no special features to combat photorespiration, such as cereals._)
**LGP for C4 crops** (_LGP stands for Length of Growing Period and is calculated as a sum of days when the average temperature is in between the absolute minimum and the absolute maximum of the selected crop.
C4 crops use the C4 carbon fixation pathway to increase their photosynthetic efficiency by reducing or suppressing photorespiration, such as maize._)
**LOGP for C4 crops** (_LOGP stands for Length of Optimal Growing Period and it is calculated as a sum of days when the average daily temperature is at the best temperatures for crop growth, between the optimal minimum and optimal maximum of the selected crop.
C4 crops use the C4 carbon fixation pathway to increase their photosynthetic efficiency by reducing or suppressing photorespiration, such as maize._)
**LGP and LOGP for C4 crops [in days]** (_LGP stands for Length of Growing Period and is calculated as a sum of days when the average temperature is in between the absolute minimum and the absolute maximum of the selected crop.
LOGP stands for Length of Optimal Growing Period and it is calculated as a sum of days when the average daily temperature is at the best temperatures for crop growth, between the optimal minimum and optimal maximum of the selected crop.
C4 crops use the C4 carbon fixation pathway to increase their photosynthetic efficiency by reducing or suppressing photorespiration, such as maize._)

And another request - could you check, if the description of factors mentioned above is correct from the language point of view? :-)...

**Comment by PavelHajek** [comment]
Great job, thanks! ;-) ... Can I ask for minor changes? Could you replace the label conditions with "related to environmental variables" and yield with "related to the length of (optimal) growing period of a crop"?
And finally, the description of units in square brackets of Soil temperatures for fertilization change into ["in days before year's end"] 
Thanks a lot ;-)...

**Comment by raitisbe** [comment]
Renaming done
